(function (matrix-multiply op1 op2 ret)
  (block
    (set ppcappcappcappcappca 0)
    (set ppcappcappcappcappcb 0)
    (if (== ppcappcappcappcappca ppcappcappcappcappcb)
      (block
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set ret 0 (+ (* (array.get op1 0) (array.get op2 0)) (* (array.get op1 1) (array.get op2 2)))))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set ret 1 (+ (* (array.get op1 0) (array.get op2 1)) (* (array.get op1 1) (array.get op2 3)))))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set ret 2 (+ (* (array.get op1 2) (array.get op2 0)) (* (array.get op1 3) (array.get op2 2)))))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set ret 3 (+ (* (array.get op1 2) (array.get op2 1)) (* (array.get op1 3) (array.get op2 3)))))))))

(function (init-matrix matrix)
  (block
    (set ppcappcappcappcappca 0)
    (set ppcappcappcappcappcb 0)
    (if (== ppcappcappcappcappca ppcappcappcappcappcb)
      (block
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set matrix 0 1))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set matrix 1 1))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set matrix 2 1))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set matrix 3 0))))))

(function (copy source target)
  (block
    (set ppcappcappcappcappca 0)
    (set ppcappcappcappcappcb 0)
    (if (== ppcappcappcappcappca ppcappcappcappcappcb)
      (block
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set target 0 (array.get source 0)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set target 1 (array.get source 1)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set target 2 (array.get source 2)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set target 3 (array.get source 3)))))))

(function (fib n)
  (block
    (set ppcappcappcappcappca 0)
    (set ppcappcappcappcappcb 0)
    (if (== ppcappcappcappcappca ppcappcappcappcappcb)
      (block
        (if (== n 0)
          (if (== ppcappcappcappcappca ppcappcappcappcappcb)
            (return 0)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (set tmp1 (array.create 4)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (set tmp2 (array.create 4)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (set exp (array.create 4)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (set value (array.create 4)))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (init-matrix exp))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set value 0 1))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set value 1 0))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set value 2 0))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (array.set value 3 1))
        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
          (set number n))
        (for
          (if (== ppcappcappcappcappca ppcappcappcappcappcb)
            (set i 1))
          (<= i n)
          (if (== ppcappcappcappcappca ppcappcappcappcappcb)
            (set i (* i 2)))
          (if (== ppcappcappcappcappca ppcappcappcappcappcb)
            (if (== ppcappcappcappcappca ppcappcappcappcappcb)
              (block
                (if (== (% number 2) 1)
                  (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                    (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                      (block
                        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                          (matrix-multiply exp value tmp2))
                        (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                          (copy tmp2 value))))))
                (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                  (matrix-multiply exp exp tmp1))
                (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                  (copy tmp1 exp))
                (if (== ppcappcappcappcappca ppcappcappcappcappcb)
                  (set number (/ number 2)))))))
        (return (array.get value 1))))))

(function (main)
  (block
    (set ppcappcappcappcappca 0)
    (set ppcappcappcappcappcb 0)
    (if (== ppcappcappcappcappca ppcappcappcappcappcb)
      (print (fib (scan))))))

