(function (merge-sort array tmp left right)
  (block
    (if (<= (- right left) 1)
      (return 0)
    )
    (set mid (/ (+ left right) 2))
    (set _ (merge-sort array tmp left mid))
    (set _ (merge-sort array tmp mid right))
    (set p left)
    (set q mid)
    (set s left)
    (for
      (set _ 0)
      (< s right)
      (set _ 0)
      (block
        (set cond (>= p mid))
        (if (< q right)
          (set cond (|| cond (< (array.get array q) (array.get array p))))
        )
        (if cond
          (block
            (set _ (array.set tmp s (array.get array q)))
            (set q (+ q 1))
          )
        )
        (if (! cond)
          (block
            (set _ (array.set tmp s (array.get array p)))
            (set p (+ p 1))
          )
        )
        (set s (+ s 1))
      )
    )
    (for
      (set i left)
      (< i right)
      (set i (+ i 1))
      (set _ (array.set array i (array.get tmp i)))
    )
  )
)

(function (main)
  (block
    (set n (scan))
    (set a (array.create n))
    (set tmp (array.create n))
    (for
      (set i 0)
      (< i n)
      (set i (+ i 1))
      (set _ (array.set a i (scan)))
    )
    (set _ (merge-sort a tmp 0 n))
    (for
      (set i 0)
      (< i n)
      (set i (+ i 1))
      (set _ (print (array.get a i)))
    )
    (return 0)
  )
)
