(function (selection-sort a n)
  (for
    (set i 0)
    (< i (- n 1))
    (set i (+ i 1))
    (block
      (set min-pos i)
      (for
        (set j (+ i 1))
        (< j n)
        (set j (+ j 1))
        (if (< (array.get a j) (array.get a min-pos))
          (set min-pos j)
        )
      )
      (set t (array.get a i))
      (array.set a i (array.get a min-pos))
      (array.set a min-pos t)
    )
  )
)

(function (main)
  (block
    (set n (scan))
    (set a (array.scan n))
    (selection-sort a n)
    (array.print a)
  )
)
